### ISSUE TITLE
Streamline Release and Push flows and documentation

### ISSUE THREAD

**Issue by charlesgreen** [simplycubed/extensions#108]
### [READ] Step 1: Are you in the right place?

Yes

### [REQUIRED] Step 2: Extension name

This is an improvement for the GitHub Actions and release flows for all packages and extensions.

### What feature would you like to see?

Streamline the process and improve the related documentation needed to create GitHub Releases, NPM releases and publish to the `simplycubed-extensions` Firebase project.

I recommend we drive releases using the `lerna version` command.
These will create releases in GitHub, which we can use to trigger npm and firebase releases.

The challenge is that versions are currently configured via the `package.json` and the `extensions.yaml` files.
I want to avoid needing to manage the `version` in these files and instead only need to use the `lerna versions` command.

We also need to document the flow.
- https://github.com/simplycubed/extensions/pull/109

**Ideal flow**
1. Merge PRs into the GitHub main branch
2. Execute `lerna version` to increment versions
3. The `lerna version` command automatically tags and creates releases in GitHub
4. The new GitHub Release triggers webflow-utils to be deployed to npm
5. The new GitHub Release triggers webflow-events-* to be published to simplycubed-extensions Firebase project.

> We need to take care in that webflow-utils is a dependency of the other projects. lerna automatically updates the webflow-utils dependency version number in the consuming project package.json files.

<img width="1035" alt="image" src="https://user-images.githubusercontent.com/1191302/213856032-df6ba770-9e3d-4137-99cc-f470f48e7853.png">

### How would you use it?

The purpose is to remove the steps needed to maintain this package and provide updates to GitHub Releases, NPM, and Firebase Extensions.

This ticket is related to #106

**Comment by anasmuhmd** [comment]
@charlesgreen Currently github release is created based version and change log. 
We can use `lerna version --conventional-commits` to generate change log as well as version update. This commit could be part of the Pull request (Like https://github.com/firebase/extensions/pull/1385/commits)
Workflows can stay the same, ie, when master branch changes, check for version changes and change log to create a new github release, as well as npm release. WDYT?

**Comment by charlesgreen** [comment]
Closed by pull #110
