### ISSUE TITLE
Convert module and target to esnext

### ISSUE THREAD

**Issue by charlesgreen** [simplycubed/extensions#127]
### [READ] Step 1: Are you in the right place?

Yes

### [REQUIRED] Step 2: Extension name

All

### What feature would you like to see?

We should consider changing the module type and target from CommonJS to esnext.
Changes are needed in the tsconfig.json and package.json

https://www.tsmean.com/articles/learn-typescript/typescript-module-compiler-option/

![image](https://user-images.githubusercontent.com/1191302/215128454-05bdcb99-8df9-45bf-af5a-d57d740028bf.png)

**Comment by anasmuhmd** [comment]
@charlesgreen I don't think we should change main to `src/index.ts` as our runtime is nodejs and typescript entrypoint would fail.

**Comment by charlesgreen** [comment]
@anasmuhmd i reviewed the li k but I do t see any references to the recommended module type.

**Comment by charlesgreen** [comment]
I just saw the following line in the link I provided however it just adds to the confusion as Vue 3 and Vuetify 3 default to esnext even though they are both written as TypeScript and the build process can be configured to run either on the server side with node or static files in the browser. 


_Using TypeScript, node.js and the TypeScript compiler option "module": "esnext" together is next to impossible. So if you're building code that should be ran with node.js, in 2020, you should still choose "module": "commonjs"._

**Comment by charlesgreen** [comment]
I merged #129 to set `"target": "esnext` for all packages.
More work is needed to better understand the setting for modules. 
Reassigning to me for now.
